### PR TITLE
bogacs's false-pool (and others)

### PR DESCRIPTION
**Pull request by kares**
adds AR-Bogacs and removes the existing AR pool hacks ... (mostly)

as noted on the updated **config.yml** template, it will only get setup with JNDI when configured e.g. : 
```yaml
  :adapter: mysql
  :jndi: 'killbill/osgi/jdbc'
  :pool: false # replaces AR's built-in pool
```

~~if this happens to look fine, I once again would like to consider avoiding some of the `pool.remove` "hacks"~~

also, tried running against MySQL as SQLite was simply dying on me (was only able to get it work cleanly with latest 3.8 which I had to actually release first) ... probably cause I'm on a different OS. 

anyways should be useful as/if more tests are added which reproduce DB specific issues.
... some spec code dry-up also got in as I was barging through failures

### CODE REVIEW

**Comment by pierre** [comment]
FYI, I've created a `kares-performance` branch tracking your branch `bogacs-plus-plus` (I'm starting to test it in our environment).

**Comment by pierre** [comment]
I've also created https://github.com/killbill/killbill-plugin-framework-ruby/wiki/AR-Bogacs-migration to share my notes/thoughts.

**Comment by kares** [comment]
thanks @pierre ... added some *notes* in the [wiki page](https://github.com/killbill/killbill-plugin-framework-ruby/wiki/AR-Bogacs-migration) (also AR-Bogacs 0.3.0 should fit)

personally, will do some more testing trying to resolve why's there a CPU slow-down ... makes no sense :crying_cat_face:

**Comment by pierre** [comment]
> personally, will do some more testing trying to resolve why's there a CPU slow-down ... makes no sense :crying_cat_face:

Quick note on my recent testing using [flood.io](https://github.com/killbill/killbill-integration-tests/blob/master/killbill-integration-tests/load/jmeter/payment.rb):

* EC2 c4.2xlarge
* RDS db.t2.medium
* Docker image killbill/killbill:13.7
* Stripe plugin
* Concurrency = 30

bogacs is doing wonders and for the first ~30' of the test, the performance holds at 1.8K tpm (for the three calls create account, add payment method and trigger purchase). The server then significantly slows down, and the CPU usage drops from 90% to 15%. :confused: 

I'll continue the investigation...

**Comment by kares** [comment]
@pierre that is exactly what I've been trying to figure out ... please let me know if you find anything.
so far been trying locally (while testing AR-JDBC) to profile but somehow I'm not reproducing reliably.

**Comment by pierre** [comment]
> The server then significantly slows down, and the CPU usage drops from 90% to 15%. :confused: 

Just to close the loop here, the issue was that my RDS instance was running out of I/O credits. Provisioning it with more space (500GB) solved the issue...

**Comment by sbrossie** [comment]
@pierre so does it mean the 'cliff' issue is solved? Or do we need additional testing to confirm?

**Comment by pierre** [comment]
Not quite. Originally, @kares reported CPU usage dropping during load tests. I ran tests for over 24hr on my laptop without being able to reproduce it. When I moved to EC2, I had huge performance issues, but it turned out it was my RDS instance being under-provisioned in terms of I/O. I ran only a 4 hrs test though, maybe I should run a longer one?

So we should still make sure @kares' original issue is fixed after https://github.com/killbill/killbill/issues/323, although he is now seeing other issues that I cannot reproduce either :confused:.  Maybe I should just :airplane: to Prague to figure it out in person? :angel:

**Comment by kares** [comment]
RDS ... had like 20GB provisioned initially and at some point (run out of SSD space) added another 30GB

would definitely be interested in numbers with the Ruby plugin (maybe with/without https: verification due https://github.com/jruby/jruby-openssl/issues/43) and >= 30 threads.

**Comment by pierre** [comment]
> RDS ... had like 20GB provisioned initially and at some point (run out of SSD space) added another 30GB

It turns out, to be able to sustain 1,500 IOPS (which was my flood test baseline), you need to provision [at least 500GB](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html#Concepts.Storage.GeneralSSD), even if you don't use the space...

> would definitely be interested in numbers with the Ruby plugin (maybe with/without https: verification due https://github.com/jruby/jruby-openssl/issues/43) and >= 30 threads.

ACK, will work on it. Stay tuned!

**Pull request merged**
